[build]
  publish = "dist"
  command = "npm run build:prod"

[build.environment]
  VITE_API_BASE_URL = "https://api.einventory.et/api"
  VITE_NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "https://api.einventory.et/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"