# ========================================================================
# KUBERNETES DEPLOYMENT
# ========================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garaadka-app
  namespace: garaadka
  labels:
    app: garaadka-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: garaadka-app
  template:
    metadata:
      labels:
        app: garaadka-app
    spec:
      containers:
      - name: garaadka-app
        image: garaadka/laundry-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: garaadka-config
              key: NODE_ENV
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: garaadka-secrets
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: garaadka-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: garaadka-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: garaadka-config
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: garaadka-config
              key: DB_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: garaadka-secrets
              key: JWT_SECRET
        - name: BCRYPT_ROUNDS
          valueFrom:
            configMapKeyRef:
              name: garaadka-config
              key: BCRYPT_ROUNDS
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}